WIP: Test that we create new draft from first deleted draft after a superseded edition
The code we've added is fetching the right edition (see console logs),
but I'm not convinced the rest of the edition creation workflow is
going to work. There's probably an `Edition.where` somewhere that
uses the default scope (which filters out deleted editions) and breaks
the draft-edition-creation behaviour.

Command:
$ govuk-docker-run rails test test/functional/admin/editions_controller_test.rb:90

Output (truncated):
```
Editions found: [[318, "superseded"], [319, "deleted"], [320, "deleted"]]
Probably last published edition = id: 319, state: deleted
E

Error:
Admin::EditionsControllerTest#test_revising_the_superseded_edition_-_if_it_happens_to_also_be_the_latest_edition_-_should_create_a_new_draft_edition_from_the_first_deleted_edition_after_the_superseded_one:
NoMethodError: undefined method `fetch_value' for nil:NilClass
    app/models/edition.rb:491:in `block in create_draft'
    app/models/edition.rb:488:in `create_draft'
    app/controllers/admin/editions_controller.rb:160:in `revise'
    test/functional/admin/editions_controller_test.rb:112:in `block in <class:EditionsControllerTest>'
```